### ISSUE TITLE
一些个人理解

### ISSUE THREAD

**Issue by kenpusney** [JimmyLv/atomic-design-react-workshop#1]
- 总体上来说，无论是否atomic design，Component driven development可以简单的看成一种buttom-up的设计和实现方法。
- 简单的实现一些atomic的组件是没问题的，但问题在于这些组件能不能变成可组合的，这样就能像写LISP一样写UI了
- （奇葩地拓展一下，编译时宏？

**Comment by kenpusney** [comment]
关于第二点，可组合组件，也就是说一部分组件并不一定是要用来做可视化啊渲染啊之类的，完全可以参与进逻辑控制，或者其他的逻辑。

当然在React里面也许并没有什么实际的用处。

**Comment by kenpusney** [comment]
哈哈刚想到个逼格更高的词，叫Higher-Order Component（

**Comment by kenpusney** [comment]
Ahh 妈蛋居然已经有了
https://facebook.github.io/react/docs/higher-order-components.html

**Comment by JimmyLv** [comment]
@kenpusney React 里面很多东西都是这么玩的，反正简化理解成一个个 function 之后就简单了。😂

比如这个 [Flow 组件](https://github.com/JimmyLv/react-workshop/blob/master/workshops/01-basics/components/Appointment.js#L5-L7)；这个 repo 里面也有，比如 [AppPage](https://github.com/JimmyLv/atomic-design-react-workshop/blob/master/src/components/pages/AppPage/AppPage.js#L11-L12) 在组合 template 的时候。

还有一个好玩的：[acdlite/recompose: A React utility belt for function components and higher-order components.](https://github.com/acdlite/recompose)
